dist: trusty
sudo: required
language: c
env:
 global:
 - OCAML_MIN=4.03.0
 - OCAML_MAX=4.07.0
 - PREDEPS="ocamlfind"
 - DEPS="camlp5 ocamlfind ppx_tools_versioned ppx_deriving ocaml-migrate-parsetree re"
 - JOBS=2

install:
 - rm -rf ~/.opam
 - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
 - echo | sudo sh install.sh
 - opam init --disable-sandboxing -j $JOBS --bare -n -y
 - opam switch create min $OCAML_MIN -y
 - eval $(opam env)
 - opam config var root
 - opam install -j $JOBS -y $PREDEPS
 - opam install -j $JOBS -y $DEPS
 - opam list
 - opam switch create max $OCAML_MAX -y
 - eval $(opam env)
 - opam install -j $JOBS -y $PREDEPS
 - opam install -j $JOBS -y $DEPS
 - opam list

matrix:
  include:

  - env: TEST="linux build $OCAML_MIN"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - lua5.1
        - gnuplot
        - gcc-multilib
    cache:
      apt: true
      directories:
      - $HOME/.opam
    script:
    - opam switch min
    - eval $(opam env)
    - make
    - make -C bench
    - make byte

  - env: TEST="linux build $OCAML_MAX"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - lua5.1
        - gnuplot
        - gcc-multilib
    cache:
      apt: true
      directories:
      - $HOME/.opam
    script:
    - opam switch max
    - eval $(opam env)
    - make
    - make -C bench
    - make byte
    
  - env: TEST="osx build $OCAML_MIN"
    os: osx
    before_install:
    - brew update
    - brew install --ignore-dependencies opam
    - brew install gnu-time
    - brew install lua51
    cache:
      directories:
      - $HOME/.opam
    script:
    - opam switch min
    - eval $(opam env)
    - make
    - make -C bench
    - make byte

  - env: TEST="osx build $OCAML_MAX"
    os: osx
    before_install:
    - brew update
    - brew install --ignore-dependencies opam
    - brew install gnu-time
    - brew install lua51
    cache:
      directories:
      - $HOME/.opam
    script:
    - opam switch max
    - eval $(opam env)
    - make
    - make -C bench
    - make byte

  - env: TEST="opam package installation"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - lua5.1
        - gnuplot
        - gcc-multilib
    cache:
      directories:
      - $HOME/.opam
    script:
    - opam switch max
    - eval $(opam env)
    - opam pin -y add elpi "https://github.com/${TRAVIS_REPO_SLUG}.git#${TRAVIS_COMMIT}"
    - ocamlfind query elpi
    - ls `ocamlfind printconf destdir`/elpi
    - which elpi
    - opam remove elpi
    - opam pin -y remove elpi
    - if ocamlfind query elpi; then false; else true; fi
    - if which elpi; then false; else true; fi
  
