dist: trusty
sudo: false
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - opam
    - lua5.1
    - gnuplot
install:
 - opam init -j 2 --compiler=4.02.3 -n -y
 - eval $(opam config env)
 - opam config var root
 - opam install -j 2 -y camlp5 ocamlfind ppx_tools ppx_deriving
 - opam list
script:
 - make
 - make -C bench
