name: Doc workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build doc

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sphinx
        run: |
          pip3 install Sphinx sphinx-rtd-theme in-place

      - name: Install ocaml
        env:
          OPAMYES: true
        run: |
          sudo apt install opam
          opam init
          opam switch create 4.09.1
          eval $(opam env)
          opam install ./elpi.opam --deps-only --with-doc

      - name: Build
        env:
          OPAMYES: true
        run: |
          eval $(opam env)
          make doc-build

      - name: Save doc artefact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: docs/build
